AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS MicronautAwsApiproxyTest API - micronaut.aws.apiproxy.test::micronaut-aws-apiproxy-test
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  MicronautAwsApiproxyTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: micronaut.aws.apiproxy.test.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: build/distributions/micronaut-aws-apiproxy-test-0.1.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  MicronautAwsApiproxyTestApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: MicronautAwsApiproxyTestApi
